### ISSUE TITLE
AsiaXpat visible popup ad

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1060]
https://hongkong.asiaxpat.com/classifieds/home-furnishings/

perhaps: hongkong.asiaxpat.com ... a[@id="fade"]

![image](https://cloud.githubusercontent.com/assets/737638/26752607/423c0358-4886-11e7-901e-d7741278ce2f.png)

**Comment by cqx931** [comment]
fixed, please check https://github.com/dhowe/uAssets/pull/50

**Comment by dhowe** [comment]
I don't see the ad anymore, but I still see a transparent overlay and a 'close advertisement' button

![screen shot 2017-06-06 at 3 00 12 pm](https://cloud.githubusercontent.com/assets/737638/26817367/deff9314-4ac8-11e7-97d6-3decd1ec8289.png)

**Comment by cqx931** [comment]
I don't see the overlay... can you see the following two entries in the logger?
![image](https://cloud.githubusercontent.com/assets/3056154/26817466/4576f060-4ac9-11e7-875f-ab92ac4c4ccf.png)

**Comment by dhowe** [comment]
![Uploading image.png…]()

**Comment by cqx931** [comment]
I don't see the two newly added filters at all...
Can you see these two filters after updating adnauseam.txt?
```
hongkong.asiaxpat.com###fade
hongkong.asiaxpat.com###light
```
