### ISSUE TITLE
Ads visible on markdown2pdf.com

### ISSUE THREAD

**Issue by ZedPea** [dhowe/AdNauseam#1265]
### Describe the issue
Ads visible on markdown2pdf.com with firefox 57, but are not visible with ublock origin

### One or more specific URLs where the issue occurs
http://markdown2pdf.com/, on either side of the page

### Screenshot in which the issue can be seen
![capture](https://user-images.githubusercontent.com/22151537/32129268-2c5c79fe-bb7d-11e7-820c-a46ca47eeb90.PNG)

### Steps for anyone to reproduce the issue
Load url
Observe ads

Disable adnauseum, enable ublock origin
Load url
No ads should be visible

### Your settings

- OS/version: Windows 7 SP1
- Browser/version: Firefox Quantum, 57.0b9 (64-bit)
- AdNauseam version: AdNauseam v3.4.202 uBlock Originv1.13.8 
- Other extensions you have installed: uBlock Origin 1.14.16 (disabled when using adnauseum of course, just to check if ads are blocked in ublock)

**Comment by dhowe** [comment]
Should be fixed @ZedPea, please verify the issue by updating your AdNauseam filters. Thanks!

**Comment by ZedPea** [comment]
Unfortunately this didn't fix doesn't appear to have worked for me. I do however see a different set of ads, not sure if that's relevant. I restarted my browser, purged the adnausem cache, and updated the filters. 

![selection_001](https://user-images.githubusercontent.com/22151537/32133538-dc4b58e0-bbd1-11e7-9792-4820443110e1.png)

This is on:

- OS/version: Arch Linux 4.13.8-1
- Browser/version: Firefox Quantum, 57.0b12 (64-bit)
- AdNauseam version: AdNauseam v3.4.202 uBlock Originv1.13.8 
- Other extensions you have installed: uBlock Origin 1.14.16 (disabled when using adnauseum of course, just to check if ads are blocked in ublock)

**Comment by dhowe** [comment]
I can't recreate this.
Can you try clicking the 'update' button next to the AdNauseam list?
@cqx931 / @greysonevins , can you try as well?

**Comment by cqx931** [comment]
The last commit doesn't fix the issue in firefox for me.
Please try this: https://github.com/dhowe/uAssets/pull/72

**Comment by ZedPea** [comment]
@cqx931's updated list works for me, whilst the other fix doesn't at least in firefox

**Comment by dhowe** [comment]
excellent, thanks for the report
