### ISSUE TITLE
Unable to type in search google dialog when active 

### ISSUE THREAD

**Issue by Clydesdale404** [dhowe/AdNauseam#1350]
### Describe the issue
Unable to type in search bar when accessing google.  This affects not only Google search but the search bar inside of gmail as well.

### One or more specific URLs where the issue occurs
https://www.google.com/search?q=Test&ie=utf-8&oe=utf-8&client=firefox-b-1

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/38569237/39067829-08d3809a-44a8-11e8-8c66-56701f96a7ac.png)

Can't tell from SS, but you are unable to click in or type in the search bar at this point.

### Steps for anyone to reproduce the issue
Using search bar in browser works and takes you to the google page, but from there you are unable to type in the search dialog. 

### Your settings

- OS/version: Windows 10 Home, Version 1709, Build 16299.371
- Browser/version: FireFox Quantum 59.0.2 64 Bit
- AdNauseam version: AdNauseam v3.5.101 uBlock Originv1.14.14 
- Other extensions you have installed: Amazon SMILE, FB Purity, Facebook Container, Greasemonkey, Imagus, LastPass, RES, FF Test Pilot, Tree Style Tab

### Your location/country
US

**Comment by cqx931** [comment]
Hi @Clydesdale404 Please update your adnauseam.txt filter for a temporary quick fix.

**Comment by Clydesdale404** [comment]
You'll need to be a bit more specific as to what I'm updating...

**Comment by cqx931** [comment]
Go to your settings page, under 3rd-party-filters, you will see `AdNauseam filters`.
Click the 'update' button besides it, and it should solve the issue for now.

**Comment by Clydesdale404** [comment]
Derp - thanks.  That fixed the login screen issues but the Videos now showing is still a problem - is that a different issue?

**Comment by cqx931** [comment]
Interesting... Let me close this ticket and we can talk over the Youtube one.
