### ISSUE TITLE
Not working at all on 9anime on Chrome/Firefox

### ISSUE THREAD

**Issue by Dyras** [dhowe/AdNauseam#1369]
### Describe the issue
Regardless of what I choose to block and regardless of my blacklist, the extension refuses to block the ads on 9anime after I refresh the website. The blocking works just fine on uBlock on both platforms.

### One or more specific URLs where the issue occurs
https://www6.9anime.is/
https://www6.9anime.is/genre/action
https://www6.9anime.is/schedule

### Screenshot in which the issue can be seen
![image](https://user-images.githubusercontent.com/12563436/42049765-441aa8be-7b07-11e8-8e79-0573bcb32c73.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Start your browser. Chrome/Firefox/Basilisk all have the issue.
2. Go onto https://www6.9anime.is/
3. Notice that the ads are everywhere.
4. Go on the same website with uBlock activated and AdNauseum deactivated.
5. Notice that the ads are gone.

### Your settings

- OS/version: Windows 10 1803
- Browser/version: Latest Firefox, latest Chrome, latest Basilisk
- AdNauseam version: Latest version. Installed the Chrome extension like half an hour ago by enabling Developer mode and I installed the Basilisk/Firefox version right from the store
- Other extensions you have installed: None on Basilisk/Firefox, a lot on Chrome. If you feel it's relevant I can make a list or disable everything except AN. I don't think it's an extension collision though.

### Your location/country
(If the issue is website specific, knowing your approximate location will help us to reproduce it)
Sweden, Stockholm.

**Comment by LamerGamer** [comment]
Same issue, Opera 53.0.

**Comment by cqx931** [comment]
It should be fixed now. https://github.com/dhowe/uAssets/commit/a5b77dfb8bfdd2e9e47a4f3e59ed1070b13c5e0d

Please go to "3rd party filters" and click the update button besides "adnauseam filters"

**Comment by Dyras** [comment]
Still happening for me.
Chrome:
![image](https://user-images.githubusercontent.com/12563436/42287385-6d11b420-7fb6-11e8-914b-02486b46e7b8.png)
![image](https://user-images.githubusercontent.com/12563436/42287389-71d0ca82-7fb6-11e8-8640-b6dd03fe8891.png)

Waterfox:
![image](https://user-images.githubusercontent.com/12563436/42287227-dd0072ae-7fb5-11e8-8d6e-ea1410fb5520.png)
![image](https://user-images.githubusercontent.com/12563436/42287218-d3b502f0-7fb5-11e8-8b6e-b71601a42c6b.png)

**Comment by cqx931** [comment]
Please see: https://github.com/dhowe/AdNauseam/issues/1376

**Comment by sandorex** [comment]
9anime changed url to https://www2.9anime.to
ads are showing again
im using firefox 64

**Comment by dhowe** [comment]
Should be fixed now.

Please go to "3rd party filters" and click the update button besides "adnauseam filters"

**Comment by sandorex** [comment]
Side ads are gone but ones in center stay
![screenshot](https://user-images.githubusercontent.com/18004075/51741642-cc39c780-2097-11e9-9faf-a10cc568733b.png)

**Comment by cqx931** [comment]
Fixed more ads from 9anime.to, please check https://github.com/dhowe/uAssets/commit/26ff69298fd39853c6eed8a8d64bccaafc29202c
