### ISSUE TITLE
Vault: repack when open and new ads are found

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1416]
After some interval has elapsed (maybe 5 seconds) following a new page is loaded, check if new ads were detected, and if so, trigger a repack in the vault (if it is open).

- [x] First, create some trigger (double-click or key-event) to repack the ads without refreshing the page
- [x] Discuss performance with @dhowe (perhaps we need to compute the ad positions for the new pack in the background, then only move the ads once finished)
- [x] Implement triggering following X seconds after each page load (if open and new ads are found)

**Comment by cqx931** [comment]
I tested it with a key-event and the speed seems to be ok for me.
However, I'm not sure repacking is the best way for a 5-second refreshing:
1. Every time the vault repacks on the same set of data, the layout changes completely. If it is going to repack itself every 5 seconds, we will end up with a 'blicking' vault
2. For larger ad set(tested with 200~ ads), the repacking time is ok, however, there will always be a second or so that we will see the ads aligning in a grid. (I haven't checked this in detail, but it would be better just showing the loading animation and get rid of this weird grid moment)

Instead of repacking, can we do add the new ads on the side of the old grid without influencing the current vault layout? (I'm not sure whether this is possible in Packery) And we could recompute zoom after adding the new ads.

**Comment by dhowe** [comment]
Comments:
1. the refresh should only happen IF there are new ads, not just every 5 seconds
1. the ads aligning first in a grid is a bug (this should never happen)
2. ~200 ads is a very small vault -- we need to test with 10 times that
4. repacking around the edges would be ideal, but a) would require a second algorithm, and b)could result in very ugly packs 
@mushon ?

**Comment by mushon** [comment]
I agree with everything here @dhowe. I think the ugly packs are one step on the right way to more elegant repacking ie #1417

**Comment by cqx931** [comment]
So I tested this time with ~2000 ads and tried to fix the aligning layout bug we had. Here are a few issues:
1. For ~2000 ads, the layout is pretty ugly. It is almost like a square and it doesn't occupy the whole screen
2.For my ~2000 ads testing, sometimes, the final layout appears at the bottom of the screen instead of the middle
3. So far what I have tested this not by just calling repack() function itself, since it won't update any new ad but just repacking the layout. What I have implemented for the test is an updateAds() function based on renderAds(). However, this method will mack any 'repack' over ~2000 ads extremely slow(~15s for the total process) because in doLayout(), it removes all the current ads and recreate all the ad divs later. Adding the ad divs is the main reason why it takes so long. 
4. There are also other jumpy weird moments when the slider just jump back to 300 for ~2000 ads, I haven't checked this in detail yet.

1) I don't think I can do much for this without changing anything in packery
2) This seems like a bug for zoom, I can check that later
3) This is the major issue in my opinion, we need a way to add new ad divs without removing everything. I propose that we could add an update parameter to doLayout(). If this parameter is true, old ad divs won't be removed and only new ads will be added, then repack will be called to repack all the ads together

**Comment by dhowe** [comment]
> we need a way to add new ad divs without removing everything. We could add an update parameter to doLayout(). If this parameter is true, old ad divs won't be removed and only new ads will be added, then repack will be called to repack all the ads together

yes, agreed -- can we simply keep the existing divs (resizing/reposition them if needed), then add new divs if needed, and set any extras (if we have less ads) to 0-size?

> Does that mean that we are only going to pass the new ads to the vault?

This would be the ideal way to do it, rather than resending all the ads that area already there...

**Comment by cqx931** [comment]
Please check:
1) Fixed layout off center issue for large grid
2) Tidy up createSlider for different cases:
default/delete/resize/update
3)For now, you can update the vault by pressing 'u', new ads should be loaded after the update
4)TODO: triggering the update event
https://github.com/cqx931/AdNauseam/commit/d163a1e233a21770bb98e6f9fc6aef02ed4cbf3d

**Comment by cqx931** [comment]
Question: should we do auto vault updating only when the time slider is set to full-width?

**Comment by dhowe** [comment]
> Can you explain more for the case "set any extras (if we have less ads) to 0-size"? @dhowe

I was thinking about the case where a user creates moves to a smaller data-range, say from 300 to 100 ads. We now have 200 extra divs which could be hidden, rather than deleted

**Comment by dhowe** [comment]
@cqx931 what browser are you testing this branch in?

**Comment by dhowe** [comment]
@mushon what browser will you use in the exhibit?
@mushon have you tested this branch yet?

**Comment by cqx931** [comment]
@dhowe @mushon  I tested it on chrome.

One more bug I noticed:
1) Update is not working if the vault starts from empty state

Yes, I still need to double check the slider for all the cases

**Comment by dhowe** [comment]
Note: we should use Firefox as our default platform for testing, as this is where most of our users are...

**Comment by mushon** [comment]
Definitely. 
In this case though, whatever will work first we will use.

**Comment by cqx931** [comment]
Please check the latest exhibition branch.
I have implemented auto vault update 3 seconds after a series ads detected(ads detected within 3seconds).

- fixed the bug for update starting from an empty vault
- autoupdate only happens if the right slider is set to the most right
- tested in firefox

**Comment by dhowe** [comment]
What is the algorithm for when an update should happen?

I still see cases where a new ad is found while the vault is open, but there is no update

Also, slider values are still not maintained after update (not sure if you've addressed this)

**Comment by cqx931** [comment]
In case 'adDetected'
1.Whenever a new ad is detected, it is added to a list of waiting Ads. This also updates the lastAdDetectedTime with the time stamp when 'adDetected' message is received
2.If the right slider is set to the most right, or when the ad is empty, call autoUpdateVault() after 3 seconds

autoUpdateVault():
If the gap between current time and lastAdDetectedTime>= 3 seconds, updateVault

slider issue was not addressed in the last fix.

**Comment by cqx931** [comment]
In the latest exhibition branch, the slider issue should be fixed for update case, I also fixed some other issues that might be the reason why sometimes the vault doesn't update when new ads are found

**Comment by cqx931** [comment]
All user interactions in vault:
zoom in with +
zoom out with -
zoom with touchpad
drag the vault
inspect ad
delete ad
drag slider

Other situations when autoUpdate should not happen:
while import ads window is open
inspecting ad mode

**Comment by dhowe** [comment]
@mushon, other cases?

**Comment by dhowe** [comment]
Works really nicely when it works! Though the update still doesn't always trigger for me. See below.

To recreate:
* open vault
* move slider right until < 5 ads are showing
* open a new tab with a page containing ads
* wait 5 seconds and notice no update

![screen shot 2018-10-30 at 1 39 03 pm](https://user-images.githubusercontent.com/737638/47698258-98dace80-dc49-11e8-962d-5dfc133f32ed.png)

**Comment by dhowe** [comment]
Also, there are some issues with the slider, which I am listing here: https://github.com/dhowe/AdNauseam/issues/1422
