### ISSUE TITLE
Ads not getting hidden when enabled (Ask)

### ISSUE THREAD

**Issue by CyrusSUEN** [dhowe/AdNauseam#153]
http://www.ask.com/web?q=fitness&qsrc=1&o=0&l=dir&qo=serpSearchTopBox
The ask.com issue only affects ADN2 on Chrome. Not uBlock Origin with the same filter lists nor ADN2 on Opera or Firefox.

http://www.zam.com/
affects ADN2 on all platforms

I've already tried to do ```git pull``` in uAssets repo before building the ADN2 extension

**Comment by dhowe** [comment]
should be fixed with ded48c51fef5

**Comment by CyrusSUEN** [comment]
![screen shot 2016-05-09 at 5 16 31 pm](https://cloud.githubusercontent.com/assets/2461812/15109411/dba21610-160d-11e6-9868-30e9280a491a.png)
On ask.com the element above is still showing.

Otherwise, it's good to be closed.

**Comment by dhowe** [comment]
please verify

**Comment by CyrusSUEN** [comment]
Ask.com text ads not getting collected nor hidden on ADN's default settings (no problem loading adnauseam filters)

http://www.ask.com/web?q=fitness&qsrc=1&o=0&l=dir&qo=serpSearchTopBox

![screen shot 2016-06-18 at 10 08 18 pm](https://cloud.githubusercontent.com/assets/2461812/16171451/ce7c0924-35a1-11e6-85c0-f7ec15a5471f.png)

no problem on www.zam.com
