### ISSUE TITLE
Ads visible on CPO magazine

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#1544]
https://www.cpomagazine.com/data-privacy/new-fbi-plans-for-social-media-surveillance-already-raising-significant-privacy-concerns/

![image](https://user-images.githubusercontent.com/737638/64152136-8bd8ce00-ce5e-11e9-8485-6c02408db197.png)

**Comment by cqx931** [comment]
Fixed. Please check @dhowe

**Comment by dhowe** [comment]
Still seeing this after I update adnauseam list:

![image](https://user-images.githubusercontent.com/737638/64235075-336f0280-cf2a-11e9-9adf-7c23a76950bb.png)

**Comment by cqx931** [comment]
Hmm, is that the only ad you see that is still there? Can you see other ads in the article?

**Comment by dhowe** [comment]
Looks good now, though it is not collected (changing the label)

**Comment by mneunomne** [comment]
Ad collection for the case seems to be fixed with the changes I am testing on this branch: https://github.com/mneunomne/AdNauseam/tree/improve-ad-collection
Created with these tests: https://github.com/dhowe/AdNauseam/issues/1838

But still better not do any merges since a lot more testing needs to be made.

**Comment by dhowe** [comment]
@mneunomne where do we stand on this?
