### ISSUE TITLE
Popups happen on 9anime.to with AN but not with uBO

### ISSUE THREAD

**Issue by Dyras** [dhowe/AdNauseam#1640]
### Describe the issue
For some reason, I get popups on 9anime.to while using AdNauseam, but I get no popups while using uBlock Origin or Nano Adblocker.

tl;dr is click this: https://9anime.to/watch/somali-and-the-forest-spirit.8r1y/wljxvo
Click on the video. You should get a popup with AN, but no popup with NA or uBO.

### Screenshot in which the issue can be seen
Compare this picture (AN): https://i.boring.host/1P01eYCF.png
To this picture (uBO): https://i.boring.host/1P03C8RU.png
Note the ad link at the bottom in the first picture, and no link in the second picture.

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)
1. Open https://9anime.to/anime
2. Choose any anime (Sometimes a popup appears here too)
3. Choose any episode
4. Click the video player to start the video
5. A popup should appear

### Your settings

- OS/version: Windows 10
- Browser/version: Latest Firefox version
- AdNauseam version: Latest release version
- Other extensions you have installed: A lot. But I don't think any of them should play a part in this. If you disagree or is unable to reproduce, I can post a list.

##### Your filter lists
Default + https://github.com/reek/anti-adblock-killer/

### Your location/country
Sweden, Stockholm.

**Comment by cqx931** [comment]
Thank you for reporting! This should be fixed in the latest commit. 

Reference: https://www.reddit.com/r/9anime/comments/exl00e/invisible_ad_issues/

**Comment by Dyras** [comment]
@cqx931 RARBG is having the same problem

https://rarbg.to/index80.php

**Comment by cqx931** [comment]
Thank you for reporting, this should be fixed after you update the adnauseam filter. 
Similar behavior, but this is caused by another script.

**Comment by Dyras** [comment]
@cqx931 This is still happening on rarbg
![grafik](https://user-images.githubusercontent.com/12563436/78425096-8b154e00-7672-11ea-9f13-87b2c084c34c.png)
