### ISSUE TITLE
[Content Warning} Cant right click ads to add them to AdNauseam

### ISSUE THREAD

**Issue by mytrash0129** [dhowe/AdNauseam#1698]
I'm not able to add ads to AdNauseam by simply right clicking them anymore

![image](https://user-images.githubusercontent.com/68516503/87884070-f4e01a80-ca0b-11ea-802e-8aa2c6301275.png)

### Steps for anyone to reproduce the issue
(Please be as detailed as possible)

### Your settings

- OS/version:
- Browser/version: Latest Firefox
- AdNauseam version: Latest 
- Other extensions you have installed: disabled them still have problems
- AdNauseam settings: default

##### Your filter lists
Default fresh install

### Your location/country
Sweden

** For adult and potential offensive sites/advertisements, please add a [Content Warning] tag in the title to warn developers that there may be offfensive material in the ticket.

**Comment by cqx931** [comment]
@mytrash0129 Thank you for reporting this issue! 
It seems like that some of old AdNauseam code is having a conflict with ublock's new "menus" permission instead of "contextMenus" in firefox. 
This is fixed at: https://github.com/dhowe/AdNauseam/commit/06dcfcabe3991c495fceae042ce9e8d79f9edc15

**Comment by mytrash0129** [comment]
Still doesn't work for me even with a fresh install. Will uninstall for now and try in a couple of days again. Keep up the good work

**Comment by cqx931** [comment]
@mytrash0129 Hi, the fix is only in the master branch at the moment and not yet published in the Firefox Store yet.
