### ISSUE TITLE
3rd party ad collection not working after 89f12eb6ce354

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#1798]
3rd party ad collection not working after https://github.com/dhowe/AdNauseam/commit/89f12eb6ce3544c847012060ad71d94b3d280dc6 __potential fix for #1771__

### How to reproduce:

Roll back to a commit before the change in the redirect rules, e.g.: https://github.com/dhowe/AdNauseam/commit/b51f155426ed1d21d6d09ae22c779a676b164fad 

And test websites such as: 
- https://www.scientificamerican.com/article/do-we-live-in-a-simulation-chances-are-about-50-50/ 
- https://www.ebay-kleinanzeigen.de/anzeigen/s-detailansicht.html?adId=1724224618

Tested in both chrome and firefox

**Comment by mneunomne** [comment]
@dhowe it seems that ad collection is back working after commit https://github.com/dhowe/AdNauseam/commit/ab2d1b3c83c620e9f28df3295aff26b500cbfd57

In both the pages mentioned above the ads are now being collected.

**Comment by mneunomne** [comment]
I pulled the lastest commit from master and it is happening again, blocking most requests instead of ADN-allowing them.

Logger from latest commit:
![Screen Shot 2021-04-14 at 16 31 37](https://user-images.githubusercontent.com/4967860/114727946-ede9fc80-9d3e-11eb-8edf-409483bafa57.png)

How it should be (from current published release):
![Screen Shot 2021-04-14 at 16 26 21](https://user-images.githubusercontent.com/4967860/114728018-00fccc80-9d3f-11eb-8027-b820f2d578b0.png)

**Comment by mneunomne** [comment]
According to my tests It stopped working again after https://github.com/dhowe/AdNauseam/commit/e195e1a0472696b1b553f3d6c1ae3a4ad06efb5e

**Comment by dhowe** [comment]
Debug logs for same comparison:

![2021-04-16 12 57 22](https://user-images.githubusercontent.com/737638/114973577-50640980-9eb3-11eb-89f8-382d74f5c333.jpg)

![2021-04-16 12 57 27](https://user-images.githubusercontent.com/737638/114973591-5528bd80-9eb3-11eb-9b66-f4676c3368c0.jpg)

**Comment by dhowe** [comment]
@cqx931 this seems related to the redirect rules, which are firing too often and/or too soon. The 'correct' version has no redirects, while the uncorrected has six (all google resources).

**Comment by cqx931** [comment]
The requests to look at are the `pagead/id` ones, `googletagmanager` is okay to be redirected as we had before.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/3056154/115083247-5e437a00-9f07-11eb-9c20-3d7722e69ff6.png">

**Comment by cqx931** [comment]
if we compare [take 2](https://github.com/dhowe/AdNauseam/commit/ab2d1b3c83c620e9f28df3295aff26b500cbfd57) and the current commit, from the logger it seems like all the ad requests just disappeared, not because anything is incorrectly blocked.

**Comment by dhowe** [comment]
@mneunomne I have merged this commit -- can you recheck?

**Comment by mneunomne** [comment]
Checked Ad collection, the logger and the console and it is back working as expecting.

**Comment by lkbr1808** [comment]
I am still having this issue, opening https://www.scientificamerican.com/article/gender-affirming-health-care-should-be-a-right-not-a-crime/ in a private window with all other extensions disabled and getting no ads detected or collected.
