### ISSUE TITLE
Incoming cookies from allowed request

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#601]
As an example:
All cookies cleared,browsing data cleared.
1. Open nytimes.com
2. We can see this request from adserver is allowed as we want to render image ad.
<img width="1029" alt="screen shot 2016-11-07 at 10 15 11 pm" src="https://cloud.githubusercontent.com/assets/3056154/20060965/a36ea0dc-a538-11e6-9b45-425db38ad98a.png">
3. There are several cookies saved in the cookies manager after loading nytimes.com and one of them is from the above adserver.
<img width="709" alt="screen shot 2016-11-07 at 10 04 09 pm" src="https://cloud.githubusercontent.com/assets/3056154/20060994/c045efda-a538-11e6-9e02-434e27fbb8fc.png">

**Comment by dhowe** [comment]
Without looking at the headers, we can't say for sure that the cookie was from the ADN-allowed request. There may have been some other connection to that server, which was neither blocked nor ADN-allowed on nytimes which generated that cookie.

For it to be a valid bug, we need to be sure that the cookie came from the request that we allowed. 

One way to do this is to create a simple test page that makes only one request to that server; then we eliminate all the other possibilities

But either way, we should use liveHTTPHeaders or similar to see which request/response contained the 'set-cookie' header that resulted in the cookie shown, otherwise we are just guessing...

**Comment by cqx931** [comment]
Another Example from nytimes.com
![screen shot 2016-11-14 at 2 50 37 pm](https://cloud.githubusercontent.com/assets/3056154/20255781/4df74068-aa7a-11e6-9fbf-530dfaf1d5a1.png)
![screen shot 2016-11-14 at 2 50 19 pm](https://cloud.githubusercontent.com/assets/3056154/20255783/519505fc-aa7a-11e6-94d1-fb4756f424e2.png)
![screen shot 2016-11-14 at 2 48 25 pm](https://cloud.githubusercontent.com/assets/3056154/20255785/570184b6-aa7a-11e6-8b5f-a7dea692e2bf.png)

**Comment by cqx931** [comment]
The set-cookies header are successfully detected,but they still get stored in the browser.
<img width="989" alt="screen shot 2016-11-14 at 2 58 25 pm" src="https://cloud.githubusercontent.com/assets/3056154/20255859/ebc93cb0-aa7a-11e6-8079-046104cffdd0.png">

**Comment by cqx931** [comment]
testcase: http://chenqianxun.com/testcases/cookieTest.html

**Comment by dhowe** [comment]
These cookies don't look the same to me (unless I am misunderstanding...) The cookie blocked in the console has the name 'S_19393001' while the one in the browser panel is 'S_19456276' 
?

**Comment by cqx931** [comment]
in the browser panel, 'S_19393001' is next to 'S_19456276'

**Comment by dhowe** [comment]
ah right, my bad... but we also need to verify that the cookie's 'content'  matches, as a similar cookie (with the same name, but different content) could also be sent...

**Comment by cqx931** [comment]
From the testing page we can see that this request is setting three cookies at the same time, and the content are the same.(And if we only open the test page, it also couldn't be anything else...)
<img width="1006" alt="screen shot 2016-11-15 at 10 21 30 am" src="https://cloud.githubusercontent.com/assets/3056154/20290836/8cca0aac-ab1d-11e6-89fe-ad3cd5d3cd27.png">
<img width="666" alt="screen shot 2016-11-15 at 10 12 43 am" src="https://cloud.githubusercontent.com/assets/3056154/20290838/8ed269c0-ab1d-11e6-9f25-995268e90d00.png">
<img width="667" alt="screen shot 2016-11-15 at 10 12 51 am" src="https://cloud.githubusercontent.com/assets/3056154/20290839/90a56cf2-ab1d-11e6-9a28-c8dd032823ce.png">
<img width="662" alt="screen shot 2016-11-15 at 10 12 57 am" src="https://cloud.githubusercontent.com/assets/3056154/20290840/92012474-ab1d-11e6-989f-8cefbe38ef7d.png">

**Comment by cqx931** [comment]
Now when I check this on test page, I can only see the allow message logged but no more [Cookies] (Block)

**Comment by dhowe** [comment]
So no [BLOCK] cookie message?

**Comment by cqx931** [comment]
yes

**Comment by dhowe** [comment]
link appears to be broken above (also can you link your test page?)

**Comment by cqx931** [comment]
http://chenqianxun.com/testcases/cookieTest.html

**Comment by dhowe** [comment]
looks like it might have to do with the capitalisation of the header name, 'Set-Cookie', rather than 'set-cookie'; take a look at core.js::line 1296

**Comment by cqx931** [comment]
hmm, but we do have `var name = headers[i].name.toLowerCase();` in line 1292

**Comment by cqx931** [comment]
<img width="689" alt="screen shot 2016-11-15 at 11 01 16 am" src="https://cloud.githubusercontent.com/assets/3056154/20291684/e20e4474-ab22-11e6-867f-320c248d902d.png">

What I found is that ` blockIncomingCookies` didn't get called at all for this case.
I am not clear why this happened, but it seems to me that CheckAllowedException is called before the allowRequest...

**Comment by dhowe** [comment]
let me take a look

**Comment by dhowe** [comment]
Should be fixed -- please verify...

**Comment by cqx931** [comment]
this specific case is solved. Let me verify it on a few sites to double check the cookies issue.

**Comment by cqx931** [comment]
http://chenqianxun.com/testcases/cookieTest2.html
I think this issue is still not completely solved, as I still get similar "undefined" type in other cases when cookies get stored.
<img width="678" alt="screen shot 2016-11-15 at 5 00 02 pm" src="https://cloud.githubusercontent.com/assets/3056154/20299280/394752da-ab55-11e6-9ee5-2bab6b9adf1c.png">
![Uploading Screen Shot 2016-11-15 at 5.00.20 pm.png…]()

**Comment by dhowe** [comment]
the issues was that the 'script' type was not registered to trigger the 'onHeadersReceived' event, so the check was never happening the way it was for images, frames, etc. I've now removed type-checking (traffic.js::line 966) altogether so that _all_ requests trigger 'onHeadersReceived', but may need to consider the performance implications of this later...

in any case, please re-verify

**Comment by dhowe** [comment]
```
module.exports = (function (settings) {

  settings.test_settings.default.desiredCapabilities.chromeOptions = {
    'extensions': [ encode("./adnauseam.chromium.crx") ]
  }
  return settings;

})(require('./nightwatch.json'));

function encode(file) {
  var stream = require('fs').readFileSync(file);
  return new Buffer(stream).toString('base64');
}
```

**Comment by cqx931** [comment]
Verified.
