### ISSUE TITLE
More problems with menu CSS

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#679]
![screen shot 2016-12-28 at 12 39 44 am](https://cloud.githubusercontent.com/assets/737638/21503988/4502efe6-cc96-11e6-876f-c31bfe3d0c76.png)

```

{
	"id": 1,
	"attempts": 1,
	"visitedTs": 1482856776271,
	"attemptedTs": 0,
	"contentData": {
		"title": "Experian® Credit Report - Official Site",
		"text": "Get Your Experian® Credit Report, Plus Your FICO® Score. Just $1 to Get Started!",
		"site": "https://r.search.yahoo.com/cbclk/dWU9MEYxRUQ1MDREMzMyNDRDNiZ1dD0xNDgyODU2Nz…257badposition%257d__kenshoo_clickid_/RK=0/RS=WlH8oDiKWSt8FMuJoiQT3tYuebM-"
	},
	"contentType": "text",
	"title": "Check Your Credit Report & FICO&reg; Score | Experian",
	"resolvedTargetUrl": "http://www.experian.com/credit-report-partner/index-g.html?sc=678645&bcd=ad…286496272_118281215255_e_{adposition}_06a2b15b-b748-48c8-aec1-a6c6b38597e6",
	"foundTs": 1482856768628,
	"targetUrl": "https://r.search.yahoo.com/cbclk/dWU9MEYxRUQ1MDREMzMyNDRDNiZ1dD0xNDgyODU2Nz…257badposition%257d__kenshoo_clickid_/RK=0/RS=WlH8oDiKWSt8FMuJoiQT3tYuebM-",
	"pageTitle": "credit at DuckDuckGo",
	"pageUrl": "https://duckduckgo.com/?q=credit&t=hs&ia=web",
	"errors": null,
	"current": true,
	"pageDomain": "duckduckgo.com",
	"version": "2.5.11",
	"targetDomain": "yahoo.com",
	"requestId": "141664"
}
```

**Comment by mushon** [comment]
fixed in https://github.com/dhowe/AdNauseam/commit/c9a4be0b5cbac9240a54784ab793a9f9b2bd483d

**Comment by dhowe** [comment]
Still seeing this (on both chrome and firefox as below):

![screen shot 2017-01-02 at 7 32 44 pm](https://cloud.githubusercontent.com/assets/737638/21588503/4881d5f2-d122-11e6-8fb9-7eaa4d280342.png)

**Comment by dhowe** [comment]
Generally speaking (not in relation to this ticket, which may be simple enough that it is clear) it is better to let one person fix a ticket, and a different person verify it (thus the 'needs-verification' label)

**Comment by mushon** [comment]
Agreed.

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On January 2, 2017 at 8:26:56 PM, dhowe (notifications@github.com) wrote:

Generally speaking (not in relation to this ticket, which may be simple enough that it is clear) it is better to let one person fix a ticket, and a different person verify it (thus the 'needs-verification' label)
