### ISSUE TITLE
Ads are being hidden on DNT sites when "Don't hide DNT" is selected

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#904]
Ex: https://duckduckgo.com/?q=credit+card&t=h_&ia=web

**Comment by dhowe** [comment]
Fixed, please verify

**Comment by cqx931** [comment]
I still see the ads hidden when I visit the page with "Do not hide DNT" checked: https://duckduckgo.com/?q=credit+card&t=hg&ia=web

**Comment by dhowe** [comment]
Hmm, I dont see that:

![screen shot 2017-03-07 at 4 16 40 pm](https://cloud.githubusercontent.com/assets/737638/23647583/89681e30-0351-11e7-8753-6fb1d7155707.png)

![screen shot 2017-03-07 at 4 16 55 pm](https://cloud.githubusercontent.com/assets/737638/23647582/894d38b8-0351-11e7-98c0-3106336c01c4.png)

**Comment by cqx931** [comment]
Shouldn't the image be opposite if this works correctly?
Don't hide DNT checked -> Ads showing up
Don't hide DNT not checked -> Ads are hidden

**Comment by cqx931** [comment]
As I think it should perform in the opposite way, here is a minor fix: https://github.com/dhowe/AdNauseam/pull/918/commits/a360ae1c6f77e09b33084785ded61f4152abe2c6
